language: go

# Disable git shallow clone. We need full history for validating copyright year of each file.
git:
    depth: false

# Golang version matrix
go:
    # Use a slightly newer version of Go than the one in oe-meta-go to allow
    # test code to use newer parts of the standard library
    - 1.11.4

install:
    # Get tools used in Makefile
    - make get-tools

before_script:
    # Print build info that binary is compiled with.
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    - echo $TRAVIS_REPO_SLUG

    # Rename the branch we're on, so that it's not in the way for the
    # subsequent fetch. It's ok if this fails, it just means we're not on any
    # branch.
    - git branch -m temp-branch || true
    # Git trick: Fetch directly into our local branches instead of remote
    # branches.
    - git fetch origin 'refs/heads/*:refs/heads/*'
    # Get last remaining tags, if any.
    - git fetch --tags origin

    # run extra checks. Tests will run as coverage tests.
    - make extracheck

script:
    - make coverage

    # Build
    - make build V=1

after_success:
    # Integrate with https://codecov.io
    - bash <(curl -s https://codecov.io/bash)

